<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MongoDB.Driver" Version="2.30.0" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <ProjectReference Include="..\SocialHub.Post.Application\SocialHub.Post.Application.csproj" />
    <ProjectReference Include="..\SocialHub.Post.Domain\SocialHub.Post.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
