<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>SocialHub.Feed.Domain</RootNamespace>
        <AssemblyName>SocialHub.Feed.Domain</AssemblyName>
    </PropertyGroup>

</Project>
