@host = http://localhost:5002
@token = paste-jwt-here
@maria = 22222222-2222-2222-2222-222222222222

GET {{host}}/health

###

POST {{host}}/api/dialogs/{{maria}}/messages
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "Привет! Ты смотрела новую схему C4?"
}

###

GET {{host}}/api/dialogs
Authorization: Bearer {{token}}
