<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SocialHub.Moderation.Application\SocialHub.Moderation.Application.csproj" />
    <ProjectReference Include="..\SocialHub.Moderation.Domain\SocialHub.Moderation.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
